In [1]:
import numpy as np

In [23]:
U = np.array([[0,0],
              [1,0],
              [0,1]])

print(U)

[[0 0]
 [1 0]
 [0 1]]


In [24]:
A = U@U.T
A

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [25]:
#get the eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)


In [26]:
print(eigvals)
print(eigvecs)

[0. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
eigvals, eigvecs = np.linalg.eig(np.eye(3)-A)
print(eigvals)
print(eigvecs)

[1. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
np.eye(3)-A

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
Q = np.eye(3)-A

print(Q@np.eye(3)@Q.T)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
eigvals, eigvecs = np.linalg.eig(np.eye(3)-2*A)
print(eigvals)
print(eigvecs)

[-1. -1.  1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
np.eye(3)-2*A

array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  1.]])